In [38]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#%matplotlib inline
from sklearn import datasets, linear_model, metrics 
# Required Packages
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
from sklearn import tree
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.externals import joblib

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import precision_score,     recall_score, confusion_matrix, classification_report,     accuracy_score, f1_score
from sklearn.feature_selection import SelectKBest

import statsmodels.api as sm  # for regression problem
import os
import sys


In [2]:
iris_dataset = datasets.load_iris()


In [3]:
print ("Iris data set Description :: ", iris_dataset['DESCR'])


Iris data set Description ::  .. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== 

In [4]:
#iris_df= pd.DataFrame(iris_dataset)
#type(iris_dataset)
X = iris_dataset.data
y = iris_dataset.target

In [5]:
tree_model = tree.DecisionTreeClassifier(max_depth=5,random_state=None)
tree_model.fit(X,y)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [6]:
tree_model.predict(X)  #get predicted value

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split


In [9]:
(train_inputs, test_inputs, train_classes, test_classes) = train_test_split(X, y, train_size=0.7, random_state=1)


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [10]:
#train_inputs
train_classes

array([2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0, 2, 2, 0, 0, 2, 0,
       2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0, 0, 0, 2, 0, 1, 2, 2, 0,
       0, 1, 0, 2, 1, 2, 2, 1, 2, 2, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 2,
       2, 0, 0, 1, 0, 2, 0, 2, 2, 0, 2, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 2, 1, 2, 0])

In [11]:
from sklearn.svm import SVC

In [19]:
#from sklearn import svm, grid_search
from sklearn.model_selection import GridSearchCV
def svc_param_selection(X, y, nfolds):
    Cs = [0.001, 0.01, 0.1, 1, 10]
    gammas = [0.001, 0.01, 0.1, 1]
    param_grid = {'C': Cs, 'gamma' : gammas}
    grid_search = GridSearchCV(svm.SVC(kernel='rbf'), param_grid, cv=nfolds)
    grid_search.fit(train_inputs, train_classes)
    grid_search.best_params_
    return grid_search.best_params_

In [15]:
import sklearn
print(sklearn.__version__)

0.20.3


In [20]:
svc_param_selection(train_inputs, train_classes,10)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'C': 10, 'gamma': 0.1}

In [21]:
svc_model_finetune = SVC(gamma=0.1, C = 10)
svc_model_finetune.fit(train_inputs,train_classes)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [24]:
predicted_test = svc_model_finetune.predict(test_inputs)
#predicted_val = svc_model.predict(X_val)

print ('Accuracy:', accuracy_score(test_classes, predicted_test))
print ('F1 score:', f1_score(test_classes, predicted_test, average='micro'))
print ('Recall:', recall_score(test_classes, predicted_test, average='micro'))
print ('Precision:', precision_score(test_classes, predicted_test, average='micro'))
print ('\n clasification report:\n', classification_report(test_classes, predicted_test))
print ('\n confussion matrix:\n',confusion_matrix(test_classes, predicted_test))

Accuracy: 1.0
F1 score: 1.0
Recall: 1.0
Precision: 1.0

 clasification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        13

   micro avg       1.00      1.00      1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


 confussion matrix:
 [[14  0  0]
 [ 0 18  0]
 [ 0  0 13]]


In [39]:
filename = 'F:/DataScience/svc_model_finetune.pkl'
joblib.dump(svc_model_finetune, filename)
 

['F:/DataScience/svc_model_finetune.pkl']

In [25]:
svc_model = SVC(gamma='auto')
svc_model.fit(train_inputs,train_classes)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [26]:
predicted_test = svc_model.predict(test_inputs)
#predicted_val = svc_model.predict(X_val)


print ('Accuracy:', accuracy_score(test_classes, predicted_test))
print ('F1 score:', f1_score(test_classes, predicted_test, average='micro'))
print ('Recall:', recall_score(test_classes, predicted_test, average='micro'))
print ('Precision:', precision_score(test_classes, predicted_test, average='micro'))
print ('\n clasification report:\n', classification_report(test_classes, predicted_test))
print ('\n confussion matrix:\n',confusion_matrix(test_classes, predicted_test))
    

Accuracy: 0.9777777777777777
F1 score: 0.9777777777777777
Recall: 0.9777777777777777
Precision: 0.9777777777777777

 clasification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.94      0.97        18
           2       0.93      1.00      0.96        13

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45


 confussion matrix:
 [[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]


In [ ]:
predicted_test = svc_model.predict(test_inputs)
#predicted_val = svc_model.predict(X_val)


print ('Accuracy:', accuracy_score(test_classes, predicted_test))
print ('F1 score:', f1_score(test_classes, predicted_test, average= None))
print ('Recall:', recall_score(test_classes, predicted_test, average= None))
print ('Precision:', precision_score(test_classes, predicted_test, average= None))
print ('\n clasification report:\n', classification_report(test_classes, predicted_test))
print ('\n confussion matrix:\n',confusion_matrix(test_classes, predicted_test))
    

In [ ]:



filename = 'F:/DataScience/svc_model.pkl'
joblib.dump(svc_model, filename)
 


In [ ]:
# some time later...
 
# load the model from disk
loaded_model = joblib.load(filename)
#result = loaded_model.score(X_test, Y_test)
result = loaded_model.score(test_inputs, test_classes)
print(result)

In [ ]:
loaded_model.predict(test_inputs)

In [29]:
#from sklearn.tree import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(random_state = 1)
modelF = forest.fit(test_inputs, test_classes)
#y_predF = modelF.predict(x_test)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [31]:
predicted_test = modelF.predict(test_inputs)
#predicted_val = svc_model.predict(X_val)


print ('Accuracy:', accuracy_score(test_classes, predicted_test))
print ('F1 score:', f1_score(test_classes, predicted_test, average='micro'))
print ('Recall:', recall_score(test_classes, predicted_test, average='micro'))
print ('Precision:', precision_score(test_classes, predicted_test, average='micro'))
print ('\n clasification report:\n', classification_report(test_classes, predicted_test))
print ('\n confussion matrix:\n',confusion_matrix(test_classes, predicted_test))
    

Accuracy: 0.9777777777777777
F1 score: 0.9777777777777777
Recall: 0.9777777777777777
Precision: 0.9777777777777777

 clasification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.94      0.97        18
           2       0.93      1.00      0.96        13

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45


 confussion matrix:
 [[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]


In [34]:
forest = RandomForestClassifier(random_state = 1)
modelF = forest.fit(train_inputs,train_classes)
#y_predF = modelF.predict(x_test)

predicted_test = modelF.predict(test_inputs)
#predicted_val = svc_model.predict(X_val)

print ('Accuracy:', accuracy_score(test_classes, predicted_test))
print ('F1 score:', f1_score(test_classes, predicted_test, average='micro'))
print ('Recall:', recall_score(test_classes, predicted_test, average='micro'))
print ('Precision:', precision_score(test_classes, predicted_test, average='micro'))
print ('\n clasification report:\n', classification_report(test_classes, predicted_test))
print ('\n confussion matrix:\n',confusion_matrix(test_classes, predicted_test)) 


Accuracy: 0.9555555555555556
F1 score: 0.9555555555555556
Recall: 0.9555555555555556
Precision: 0.9555555555555556

 clasification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

   micro avg       0.96      0.96      0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45


 confussion matrix:
 [[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [32]:
n_estimators = [100, 300, 500, 800, 1200]
max_depth = [5, 8, 15, 25, 30]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10] 

hyperF = dict(n_estimators = n_estimators, max_depth = max_depth,  
              min_samples_split = min_samples_split, 
             min_samples_leaf = min_samples_leaf)

gridF = GridSearchCV(forest, hyperF, cv = 3, verbose = 1, n_jobs = -1)
bestF = gridF.fit(test_inputs, test_classes)

Fitting 3 folds for each of 500 candidates, totalling 1500 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   16.6s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.6min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.2min
[Parallel(n_jobs=-1)]: Done 1500 out of 1500 | elapsed:  8.7min finished
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [33]:
bestF.best_params_

{'max_depth': 5,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 100}

In [36]:
forest = RandomForestClassifier(max_depth = 5, min_samples_leaf = 2, min_samples_split = 2, n_estimators = 100, random_state = 1)
modelRF_finetune = forest.fit(train_inputs,train_classes)
#y_predF = modelF.predict(x_test)

predicted_test = modelRF_finetune.predict(test_inputs)
#predicted_val = svc_model.predict(X_val)

print ('Accuracy:', accuracy_score(test_classes, predicted_test))
print ('F1 score:', f1_score(test_classes, predicted_test, average='micro'))
print ('Recall:', recall_score(test_classes, predicted_test, average='micro'))
print ('Precision:', precision_score(test_classes, predicted_test, average='micro'))
print ('\n clasification report:\n', classification_report(test_classes, predicted_test))
print ('\n confussion matrix:\n',confusion_matrix(test_classes, predicted_test)) 


Accuracy: 0.9555555555555556
F1 score: 0.9555555555555556
Recall: 0.9555555555555556
Precision: 0.9555555555555556

 clasification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

   micro avg       0.96      0.96      0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45


 confussion matrix:
 [[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
